name: Python on Ubuntu

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '43 6 * * 1'

jobs:
  ubuntu_builtin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # ubuntu:latest  --> most recent LTS release
        # ubuntu:rolling --> most recent release
        container: ["ubuntu:latest", "ubuntu:rolling"]
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
            build-essential \
            git \
            git-lfs \
            libffi-dev \
            python3-full \
            python3-dev \
            python3-pip \
            python3-setuptools \
            automake \
            autoconf \
            libtool
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          python3 -m venv venv && \
          . venv/bin/activate && \
          pip3 install .
      - name: Test
        run: |
          . venv/bin/activate && \
          pip3 install pytest && \
          py.test
